project_id = "uruqmzpihbxzzowrsrny"

[functions]
  [functions.analyze-property]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.enhance-property-content]
    verify_jwt = false
  [functions.mortgage-enquiry]
    verify_jwt = false
  [functions.detect-focal-point]
    verify_jwt = false
